name: SonarQube Scan

on:
  push:
    branches:
      - mastre

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarScanner using Docker
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'http://localhost:9000'  # Replace with your SonarQube server URL if different
        run: |
          docker run --rm \
            -e SONAR_HOST_URL=$SONAR_HOST_URL \
            -e SONAR_LOGIN=$SONAR_TOKEN \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=TESTrepo \
            -Dsonar.projectName=TESTrepo \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=/usr/src
