name: SonarQube Scan

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  
jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        run: |
          sonar-scanner \
            -Dsonar.projectKey=TESTrepo \
            -Dsonar.projectName=TESTrepo \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
